store/heightsub.go
store/store.go
store/store_test.go

Found while debugging some rollkit tests. Not critical and can only happen in tests 
Supposed to be merged as two separate commits.

Publish initial head via heightSub and use native atomic type

---

p2p/session.go

Empty responses shouldn't be logged out as an error, it happens often on connection issues.

refactor: reduce empty response to DEBUG log

---

p2p/exchange.go
p2p/options.go

Implementing this proposal https://github.com/celestiaorg/go-header/pull/28#issuecomment-1509951953 instead of https://github.com/celestiaorg/go-header/pull/28

chore(p2p): remove TrustedPeersRequestTimeout config field

---

p2p/options.go
p2p/options_test.go
store/options.go
store/options_test.go
sync/options.go
sync/options_test.go

Adds option to set ___the entire___ Parameters structure for each component.
For more context, see https://github.com/celestiaorg/go-header/pull/30#issue-1670071993 and https://github.com/celestiaorg/go-header/pull/30#issuecomment-1510449680.

feat: WithParams option for every component

---

p2p/exchange_test.go
sync/sync.go
sync/sync_getter.go
sync/sync_getter_test.go
sync/sync_head.go
sync/sync_head_test.go

Closes: #67 
The issues:
* The syncGetter usage was racy. It had working single-flight protection, but all the routines awaiting the result returned all together and set the new header, causing the Store to receive the same headers awaited routines amount of time. 
* The race between headers received from gossip and requested by Head callers.

fix(sync): fix two synchronization issues

---

store/store.go
store/store_test.go

Fix panic by reworking the condition that compares `from` and `to`
Closes #70

bugfix: fix panic in GetVerifiedRange

---

store/heightsub.go
store/store_test.go

We should allow the Store to be started from any desired height, not only 1.

fix(store): ensure Store can be initialized with any height

---

headertest/dummy_header.go
sync/sync_test.go

Implement test for the case where a bad header is set as a sync target and ensure that syncer can discard and recover from it.

test(sync): Test case where bad header is set as sync target

---

sync/sync_head.go

returning subjective head if request to trusted peer for head fails

---

errors.go
headertest/subscriber.go
interface.go
p2p/subscriber.go
p2p/subscription_test.go
sync/sync.go
sync/sync_head.go
sync/sync_head_test.go
sync/sync_test.go

* Verifier is the more correct term to use for stateful verification
* Set because in fact we currently allow only one verification func
* Remove dependency pubsub to support returning header.VerifyError
NOTE: This breakage does not affect anyone as the only user of SetVerifier is Syncer which is updated in this PR

refactor!: Subcriber: AddValidator -> SetVerifier

---

header.go
p2p/exchange.go
p2p/session.go
p2p/session_test.go
p2p/subscriber.go
store/init.go
store/store.go

Header implementations should not call Validate themselves as the lib now controls it.
Additionally, we unify the response processing code and Header constructor.
Closes #78
Based on #88

fix: ensure header.Validate is called by the lib 

---

headertest/store.go
interface.go

It's net negative to enforce life cycling methods on the interface.
Closes #6

fix!: remove lifecycle methods from the interface

---

header.go
headertest/dummy_header.go
headertest/store.go
interface.go
metrics.go
p2p/exchange_test.go
p2p/server.go
store/batch.go
store/height_indexer.go
store/heightsub.go
sync/sync_head.go
sync/sync_test.go
verify.go

refactor!: make Header.Height uint64

---

sync/sync_head.go

This PR addresses #102.
The buffer should be generous enough to account for variable block time which may come out to average below that which is defined on the syncer.

fix(sync): Allow generous buffer for heightThreshold calculation to account for variability in block time

---

headertest/dummy_header.go
opts.go
p2p/exchange.go
p2p/exchange_test.go

fix(p2p): Head requests respects SoftFailure during Verify check

---

p2p/exchange.go

Currently, the exchange will block peers for giving a bad header that does not pass the `Verify` check (unless it is a `SoftFailure`). Unless we introduce another field inside of `VerifyError` to indicate to the caller whether the error was severe enough to warrant blocking, we shouldn't blanket block for verify errors as a good peer that sends a slightly outdated header will get banned. 
(this is currently observable on `arabica` - have not tested on mocha yet)
**Moral of the story: do not prematurely implement blocking behaviour.**

fix(p2p/exchange): Remove peer blocking from head request

---

sync/sync_head.go

While this is a quick fix to prevent the syncer from doing additional unnecessary work (eagerly requesting a new Head from the network), the proper solution here would be to implement metrics to gain better insight into average block time of the network **and** to allow the `recencyThreshold` to be determined based on an average time of the last n amount of blocks.

fix(sync): allow a greater buffer for recency threshold default

---

p2p/exchange.go
p2p/helpers.go
p2p/metrics.go
p2p/options.go
p2p/subscriber.go
p2p/subscription_test.go
sync/options.go
sync/sync.go

* Adds params and options for Subscriber
* NetworkID was optional in other places besides Subscriber.
* Fixes issue with optional network id where it results in '//'
* Unifies optionality for metrics
* Before we called InitMetrics on the component, while we could leverage existing options
* Thus it's breaking. We wanted to break Getter interface anyway.
* Fixed old breaking TODO

feat(p2p)!: parameters for Subscriber

---

headertest/store.go
interface.go
local/exchange.go
p2p/exchange.go
p2p/exchange_test.go
p2p/server.go
p2p/server_test.go
p2p/session.go
store/store.go
store/store_test.go
sync/sync.go
sync/sync_getter_test.go
sync/sync_head_test.go
sync/sync_test.go

Merges `GetVerifiedRange` functionality into `GetRangeByHeight` (breaks `GetRangeByHeight` signature and removes `GetVerifiedRange`)
No need for two methods doing the same thing.
Also introduces `GetRange` on `store.Store` interface to allow requesting local headers without passing in a `fromHead` for verification - this prevents p2p server from needing to perform an additional read (to get the `fromHead`) from the store to perform the `GetRangeByHeight` request.

refactor!: Merge `GetVerifiedRange` and `GetRangeByHeight` in Getter interface and remove redundant endpoint

---

sync/metrics.go
sync/options.go
sync/sync.go

refactor(sync)!: use options to init metrics

---

p2p/exchange.go
p2p/metrics.go
p2p/subscriber.go
p2p/subscription_test.go
sync/metrics.go
sync/sync.go

I treated metrics initialization as like it's being run in `init` while it's not. Even if these are programmer bug errors, metrics initialization will happen after some other components have started, causing various artifacts if not stopped gracefully.

fix!: handle error on metrics

---

p2p/subscriber.go
p2p/subscriber_metrics.go
p2p/subscription.go

Adds 4 metrics:
* messageSize - Histogram
* messageNum (Accepted/Ignored/Rejected) - Int64Counter
* messageTime - Histogram
* subscriptionNum - AsyncGauge
TODO - Graphana Dashboard

feat(p2p): metrics for Subscriber

---

p2p/server.go
p2p/server_metrics.go

Includes:
* headersServed
* headServeTime
* rangeServeTime
* getServeTime
Depends #125

feat(p2p): metrics for ExchangeServer

---

p2p/peer_tracker.go
p2p/peer_tracker_test.go

Adds `minPeerTrackerSizeBeforeGC` setting to peer tracker, that specifies the min amount of peers before the peerTracker starts removing peers.

feat(peer-tracker): add minAmount of peers tracked in tracker

---

headertest/store.go

Self explanatory. Found during pruner service testing.

fix(headertest): Store should fail if a range of 0 is requested

---

p2p/exchange_metrics.go
p2p/subscriber_metrics.go

Previously some metrics did not work in the p2p package because Otel does not allow registering multiple callbacks per `otel.Meter` instance. At some point tracked/disconnected/blocked metrics were overwritten by subscription metric callback. Added single `metric.Registration` in exchange client and created a separate instance for subscriber metrics.

fix(p2p): fix metrics in p2p package

---

headertest/store.go

Self explanatory, found during testing.

fix(headertest): Return ErrNotFound in header store if not found

---

sync/sync_head.go

Set timeout to avoid the syncer being stuck on the Head request if the other node is unresponsive.

fix(syncer): set timeout for head request

---

sync/metrics.go
sync/sync.go
sync/sync_head.go

feat(syncer/metrics): add metrics to syncer

---

store/store.go

The log output has been updated for a better troubleshooting experience when writing a batch of headers. Previously, when an error occurred, the log provided 'from' and 'to' ranges without specifying the actual error. Now, the 'err' parameter has been added to provide more information about the exact issue.

fix(store): add error details to log output during header batch write

---

p2p/subscriber.go

[This PR](https://github.com/celestiaorg/celestia-node/pull/2882) was caused by the fact that we now no longer ignore the error from unregister topic validator. 
@Wondertan brought up a good point that the API of `Subscriber` doesn't enforce `SetVerifier` so it's possible to successfully Start the Subscriber without mounting a validator on it, but Stop would fail due to no validator being present. 
This PR reverts the change and logs/ignores the error from unregister topic validator.

refactor(p2p): subscriber.Stop logs but ignores error from unregister topic validator

---

sync/metrics.go
sync/sync_head.go

This PR renames a poorly named metric from `unrecent_header` to `outdated_head` which is more descriptive / accurate. 
It also cleans up a bit of the code inside of `sync_head.go`.
This PR is meant to override #162 if we agree that the timeout should not be configurable (see [comment](https://github.com/celestiaorg/go-header/issues/155#issuecomment-1983516622)

chore(sync)!: Rename `unrecentHead` to `outdatedHead` in metrics + clean up `Head` func a bit

---

p2p/peer_tracker.go

We were waiting for all bootstrapper connections to either fail or succeed. The side effect of this approach is that a single connection may stall for various reasons, preventing the Exchange client from starting in an adequate amount of time. 
This patch ensures that every connection attempt has a generous timeout of 1m and that connections are not blocked for startup. We don't, in fact, need to wait for any connection to succeed and continue application startup. This also optimizes the startup time in the best case, as the application would be able to operate with new connections as they come and established, instead of waiting for the whole group of bootstrapper connections to either fall or succeed.

fix(p2p): make bootstrapping non-blocking

---

p2p/peer_tracker.go

The context was canceled before we performed any connection during bootstrap.

fix(p2p/peerTracker): fix bootstraping

---

p2p/exchange.go
p2p/peer_tracker.go
p2p/peer_tracker_test.go

Removed timeout during bootstrap, as we agreed in dm. Also, instead of relying on the exchange context, bootstrap now relies on the peerTracker context.

fix(p2p/peerTracker): remove timeout during bootstrapping 

---

p2p/session.go
p2p/subscriber.go

This protects the library from potential dos vectors introduced by go-header users in the header deserialization and verification code paths.

fix(p2p): preemptive panic recovery

---

go.mod
go.sum
store/height_indexer.go
store/store.go

This PR updates the major version of `github.com/hashicorp/golang-lru` from `v1` to `v2`. The biggest improvement is support for generics. So, we can experience a bit better performance due to fewer allocations than `v1` (where every value was wrapped in `interface{}`, which causes allocation in most cases).
I'm not sure if I should prove my words with benchmarks 'cause the `golang-lru` authors didn't post any benchmarks. 
Also here: moving from ARC cache to 2Q (two queue) to avoid potential issues with ARC patent.

deps: bump hashicorp/golang-lru to v2 and move from ARC to 2Q cache

---

store/store.go
store/store_test.go

We don't need to verify headers on every `GetRangeByHeight` 'cause verification already happened in `Append`. No tests failed, added `TestStore_Append_BadHeader` to prevent bugs in the future.
Fixes #135

fix(store): stop doing header verification in GetRangeByHeight

---

store/init_test.go
store/store.go
store/store_test.go
store/testing.go
sync/sync_head_test.go
sync/sync_test.go

Drop `store.NewStoreWithHead`. Replace it with a test helpers where appropriate. `store` package now has `newStoreWithHead`, `sync` has `newTestStore`. Both now require `tb testing.TB` as a 1st param which simplifies usage for the future tests and benchmarks.
Fixes #188

refactor(store,sync)!: drop `NewStoreWithHead`

---

sync/sync.go
sync/sync_head.go

Make `store` field usage explicit. Plus `storeHeaders` was just a wrapper around `store.Append` without any logic.

refactor(sync): drop storeHeaders helper

---

p2p/exchange.go
p2p/helpers.go
p2p/session.go

`sendMessage` was doing a bit too much, observability could happen on the caller side, which easier to adapt and extend in the future.
Also, dropping 1 `if` in `processResponses` 'cause it's always `false`. And slice prealloc, looks harmless.

refactor(p2p): simplify sendMessage

---

interface.go
store/heightsub.go
store/store.go
sync/sync_head.go
sync/sync_store.go

Things that gonna change after we drop adjacency requirement from `Store.Append`:
- Obviously dropping `ErrNonAdjacent` (breaking change).
- `Store.Append` comment is **already** outdated (looks like there were 2 return params)
- `store.Store.Append` will not verify for adjacency (obviously)
- `Syncer.setSubjectiveHead` will not verify for `ErrNonAdjacent`
- adjacency check is happening in `sync` instead of `store`.
Fixes #32

feat(sync, store)!: Remove adjacency requirement from Store.Append

---

.golangci.yml
Makefile
header.go
p2p/server.go
p2p/session.go
store/keys.go
sync/sync_head_test.go

Unify formatting with `celestia-node` and other Celestia projects in the future.

chore: use gofumpt

---

p2p/exchange.go
p2p/exchange_test.go
p2p/options.go
p2p/options_test.go
p2p/server.go
p2p/server_test.go

We were missing request timeout for 1 handler. Fixing it + adding timeout tests.
Also, renaming `RangeRequestTimeout` to `RequestTimeout` for consistency.

fix(p2p)!: use request timeout

---

hash.go
hash_test.go

Reduce a bit of allocations and cpu time in `Hash` arshaling methods. Same behaviour as before but slightly in another way: instead of operations on `string` we can do this on `[]byte`. As a result we now have tests for that.
```
go-header % go-perftuner bstat a.txt b.txt
args: [a.txt b.txt]name                         old time/op    new time/op    delta
HashMarshaling/String-10        798ns ± 0%     613ns ± 0%  -23.08%  (p=0.002 n=6+6)
HashMarshaling/Marshal-10      1.11µs ± 0%    0.84µs ± 0%  -24.55%  (p=0.004 n=5+6)
HashMarshaling/Unmarshal-10     333ns ±11%     277ns ± 1%  -16.92%  (p=0.004 n=5+6)
name                         old alloc/op   new alloc/op   delta
HashMarshaling/String-10         192B ± 0%      128B ± 0%  -33.33%  (p=0.002 n=6+6)
HashMarshaling/Marshal-10        296B ± …
```

perf: faster hash marshaling methods

---

.github/workflows/go-ci.yml
sync/sync_head.go
sync/sync_test.go

Make it easier to understand. Also, slightly increasing sleep duration in `sync.TestSyncSimpleRequestingHead` to make test less flaky.

refactor(sync): simplify isExpired

---

store/store.go
store/store_test.go

Add `tailHeader` as a part of backward sync. Currently it's initialized to initial header and isn't exported. Harmless addition to simplify future PRs.

feat(store): add tail header

---

store/store.go

Before this PR when we fail to write a batch we just ignore it. Adding retries + backoff to try a few times.
Fixes #209

feat(store): flush loop retries and backoff

---

store/keys.go
store/store.go

Adding method that will return tail header from the underlying datastore when `Store[H]` will be started. Similar to `readHead` method in `Store[H]`.
Should be merged after #210

feat(store): add readTail method

---

headertest/verify_test.go
p2p/exchange.go
sync/sync_head.go
verify.go

Remove `heightThreshold` check in `Verify` func.

feat(verify): remove height check in Verify

---

headertest/store.go
interface.go
p2p/server_test.go
store/store.go
store/store_test.go

Add `.Tail` method to `header.Store[H]` and `store.Store[H]` implementation. For now method tries to return genesis header. In the future PRs method will start returning real tail of the store.
Updates #203

feat(store): add Tail method

---

store/heightsub.go
store/heightsub_test.go
store/store.go
store/store_test.go
sync/sync_head_test.go
sync/sync_test.go

The main idea of this PR is to make `Store[H].Head` working properly, to be precise: returning head that was written to the disk (*). Along with that `heightSub.height` is increased monotonically to prevent bugs when we have store appends out of order.
To test everything I'm adding 2 new tests: one that verifies out of order appends and another when which does this concurrently. Which helped to find 2 or even 3 edge cases during coding.
Fixes #201

fix(store): properly update store head

---

store/store.go
store/store_test.go

This PR cleans up a sanity check on the range request in the private method of store to make it more readable.

"readability"fix(store): Clearer range check

---

p2p/subscriber.go
p2p/subscription_test.go

A subscription might be started without the PubSub validator fully registered, causing nil pointer deref. This was observed as a flake in tests and sometimes even on the celestia node start. It's time to fix this issue altogether. 
The naive fix would check for nil, discarding a valid header message. On the other hand, this fix ensures proper order of events, guaranteeing that a valid message is never processed by subscription before the user's header verifier is set.
Related to https://github.com/celestiaorg/celestia-node/issues/4001

fix(p2p): catch rare nil Header

---

p2p/server_test.go
store/batch.go
store/heightsub.go
store/heightsub_test.go
store/metrics.go
store/store.go
store/store_test.go
sync/sync_test.go

- Introduce a new unexported `Store` field which tracks the highest contiguous header observed.
- Rework `heightSub` to work only with height and not headers (drastically simplified internals and API)
- Load `headKey` on `Store.Start`
- `Store.Head` is much simpler, again
- `batch` will be reworked in the next PR.
Fixes #201

fix(store): track store's contiguous head

---

sync/sync_head.go
sync/sync_head_test.go

We don't need recursion here. If recent head request fails, all the waiters should simply return any known subjective head, like with other error cases.
Closes https://github.com/celestiaorg/go-header/issues/247

fix(syncer): don't Head recursively

---

verify.go

In celestia-node, when a header comes through headersub that may be one header height behind (due to a slow broadcaster), where our subjective head is ahead of the incoming net head by 1, we actually catch that error due to its timestamp:
`
2025-03-19T14:37:16.320+0100	WARN	header/sync	sync/sync_head.go:181	invalid network header	{"height_of_invalid": 26314, "hash_of_invalid": "D5137A04DD552639D05D9369DE685C1F11B7D85FFCBDA0E54E66E55978C18000", "height_of_subjective": 26315, "hash_of_subjective": "6D968C6ED4C8B7B1B5EC1F883E11A02EFD3832DBDF2FD3AB9F9D8F3592227BA0", "reason": "unordered headers: timestamp '2025-03-19T13:36:53Z' < current '2025-03-19T13:37:02Z'"}
`
rather than just catching it via the height check. 
This PR reorders the check so that the error is more clear when this actually …

fix(verify.go): Re-order the checks in order of sanity-check severity

---

p2p/subscriber.go
p2p/subscription_test.go

Blocked on https://github.com/libp2p/go-libp2p-pubsub/pull/603

perf(p2p): avoid deserialization for locally published headers

---

header.go
headertest/dummy_header.go
sync/metrics.go
sync/sync_head.go
sync/sync_head_test.go

feat(sync): bifurcation for syncTarget

---

headertest/verify_test.go
local/exchange.go
p2p/session.go
p2p/session_test.go
store/store.go
store/store_test.go
sync/sync.go
verify.go

Removes verification out of the Store => requires local exchange to do verification => extracts canonical VerifyRange with unit testing => uncovers minor edge cases with range verification
Closes #266

refactor: extract VerifyRange and remove verification out of store

---

store/store.go
store/store_test.go

Previously Store allowed deleting up to the Head. This change allows deleting including the head too, ensuring proper cleanup of Store's state in such a case. If head is `5` and `DeleteTo(6)` is called, the store will handle this case now.
Additionally, if head was `5` and `DeleteTo(7)` is called, while `7`and `8` exists in the store, they will become Tail and Head respectively. 
Closes #284

fix(store): support complete erase

---

sync/syncer_tail.go

A non-nil but empty hash could be passed, so check the len

fix(syncer): check tail hash via len

---

sync/syncer_tail.go

* Finding a new tail in the regular case (not subjective init) only relied on old tail. In the worst case, where the old tail is 1, the estimation results are inaccurate. The fix is to dynamically decide what to estimate with (head or tail) basing on the time diff between old and expected tails
* When confirming the estimation by looking at the actual header, the comparison was wrong

fix(syncer): fix time comparison and improve estimation accuraccy

---

store/store.go
store/store_delete.go
sync/syncer_head.go

* Fixes leftover bug from #326 
* refactors store wiping case to avoid silent failure for setTail
* fixes two bugs in deleteRange
* context shadowing bug causing context to cancel prematurely
* closed of a closed channel panic when multiple workers error
*  error wrappings
* more logging improvements

misc(store): various fixes and chores

---

sync/syncer_head.go

During subjective init, we verify the head against the tail. However, the tail may be configured to be outside of the trusting window, causing subjective init "deathloop". 
Once the tail is requested, it is immediately stored as the first-ever header. However, this tail is also a head for a brief moment before the network head gets applied in `incomingNewHead`. And when `verify` inside of it calls `subjectiveHead`, the temporary head tail is considered expired, causing re-requesting of the new head. However, this new head fails verification as it's the same as the network head awaiting to be applied. Then this whole process goes nuts in cycles.
This is actually also a solution for the original problem described in #317, but it does not solve the secondary problem in the EDIT section, so …

fix(sync): subj init death loop
