celestiaorg/go-header

.gitignore
=> chore: Add `.gitignore`

p2p/exchange.go, p2p/exchange_test.go
Supersedes @vgonkivs PR #20 and adds "sleeps" between retries.
=> feat(p2p): Implement retries for requests

README.md, headertest/dummy_header.go, headertest/dummy_suite.go, headertest/store.go, headertest/subscriber.go, p2p/exchange_test.go, p2p/server_test.go, p2p/session_test.go, p2p/subscription_test.go, store/heightsub_test.go, store/init_test.go, store/store_test.go, store/testing.go, sync/ranges_test.go, sync/sync_getter_test.go, sync/sync_store_test.go, sync/sync_test.go
Improves testing utilities from multiple perspectives. Breaking
=> refactor(headertest)!: unify, prettify and generify testing utilities

Makefile, go.mod, go.sum
Tested that it does not break node nor it changes the generated proto files
=> fix: avoid replacing proto dep and add pb-gen makefile rule

p2p/exchange.go, p2p/peer_tracker.go, p2p/peer_tracker_test.go
Splitting out changes from https://github.com/celestiaorg/celestia-node/pull/1548
=> refactor(p2p): Peer tracker respects context on Stop

p2p/exchange.go
=> move trusted peer check to performRequest from the exchange constructor

store/keys.go, store/options.go, store/store.go
=> store: Parameterize store prefix

README.md
Closes https://github.com/celestiaorg/go-header/issues/61
=> docs: fix grammar

sync/sync.go
Change error type to string in order to marshal/unmarshal it correctly
closes #66
=> bug(sync): change error type to string

sync/sync_getter.go
=> chore(sync): Rename a variable inside sync_getter for better readability

sync/sync.go
Added json tags for sync.State
Partly fixes https://github.com/celestiaorg/celestia-node/issues/2427
=> feat(sync): add json tags

sync/sync.go
Restore error if sync finished successfully
=> fix: fix issue with error restoring in syncer

p2p/exchange.go
=> chore(p2p): add height to log for head verification failure

headertest/store.go
=> fix(headertest): sanity check range

.github/CODEOWNERS
Adds @walldiss @ramin @cristaloleg to CODEOWNERS
=> add @walldiss @ramin @cristaloleg to CODEOWNERS

verify.go
Leftover after https://github.com/celestiaorg/go-header/pull/216
=> !chore: drop DefaultHeightThreshold

.github/CODEOWNERS
=> chore: remove ramin from CODEOWNERS

store/heightsub.go, store/heightsub_test.go, store/store.go, store/store_test.go, sync/sync_head_test.go, sync/sync_test.go
This reverts commit 18f0eb1c5d3aeab6476123da0dad57e82c067984. (#207)
=> Revert "fix(store): properly update store head (#207)"

store/heightsub_test.go
Coming out as a result of reviewing #239
=> test(store): add multi-subscription heightSub testcase

interface.go, p2p/server_test.go, store/options.go
Reduce defaults to be more sane.
=> params(store): Change default cache size for StoreCache + WriteBatch

p2p/server_test.go, store/batch.go, store/heightsub.go, store/heightsub_test.go, store/store.go, store/store_test.go, sync/sync_test.go
Cherry-pick of https://github.com/celestiaorg/go-header/commit/f41d9f55759cd0c98946e24681e6e5429e911ea5
=> feat(store): adjacency fix

interface.go, p2p/server.go
=> fix: add header range mix up check

headertest/store.go, interface.go, p2p/server_test.go, store/batch.go, store/height_indexer.go, store/keys.go, store/store.go, store/store_test.go
=> feat!(store): add DeleteTo and update tail accordingly

store/store.go
There are some places when we return error from datastore. However, there are places where we replace not found error with our `header.ErrNotFound`. 
Aligning all datastore calls to the same behaviour. Also, changed 2 places to use `hashKey` helper.
=> fix(store): return `header.ErrNotFound` where appropriate

p2p/session.go
=> fix(p2p): add correct header length validation

p2p/subscriber.go, sync/ranges.go
=> fix: use proper log functions

store/store.go
Small updates after recent merges.
=> chore(store): small DeleteTo updates

p2p/server.go, p2p/session.go, sync/metrics.go, verify.go
=> chore: do lint

store/metrics.go, store/store.go, store/store_test.go
Closes #282  and adds new tail metric
=> feat(store): advance tail

.github/CODEOWNERS
=> chore(CODEOWNERS): remove @cristaloleg

store/batch.go, store/store_test.go
=> fix(store): support intermittent writes for batch

store/store.go, store/store_test.go
=> fix(store): Tail aware HasAt

sync/syncer_head.go, sync/syncer_tail_test.go
A minor improvement to readability, performance, and correctness.
This change makes `networkHead` report if a new head was requested, following a similar pattern in `subjectiveHead`.  This, in turn, allows skipping `subjectiveTail`, guaranteeing that tail changes only when a new head arrives. Similarly, we prevent re-verifying the current head in `incomingNetworkHead` on every new' Head' call.
=> fix(sync): move tail only if head changes

store/store_recover.go
Unsafe tools to manipulate the store's state
=> feat(store): store recovery tools
